title: Texture Theme
author: Angela Zhao
email: azhao29@jh.edu
description: > # this means to ignore newlines until "show_exerpts:"
  Politeness related Text-Style-Transfer
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this

permalink: /:title/
texture:
  title: Angela Zhao
  tagline: 
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  # showPicker: true

  # generate social links in footer
  social_links:
    # twitter: 
    github:  ang-zhao
    linkedIn: in/angela0zhao
    # rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md

# Build settings
remote_theme: samarsault/texture

plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-remote-theme