project:
  type: website
  output-dir: docs
  resources: resume_AngelaZhao_Jun1_2025.pdf
  
website:
  title: "Angela Zhao"
  navbar:
    collapse-below: xl
    collapse: true 
    search: true
    logo-href: index.qmd
    right:
      - education.qmd
      - publications.qmd
      - work.qmd
      - text: "Adaptive Trading Dashboard"
        href: https://adaptive-trading.streamlit.app/
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?hl=en&user=Vc9Pn4YAAAAJ
      - icon: github
        href: https://github.com/ang-zhao?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/angela0zhao/
        
format:
  html:
    theme: lux ## minty also good
    linkcolor: MediumAquaMarine
    css: styles.css
    toc: true

editor: visual

options:
  warning: false
