project:
  type: website
  output-dir: docs
  resources: resume_AngelaZhao_Sep1.pdf
  
website:
  title: "Angela Zhao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - publications.qmd
      - work.qmd
    right:
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?hl=en&user=Vc9Pn4YAAAAJ
      - icon: github
        href: https://github.com/ang-zhao?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/angela0zhao/
        
format:
  html:
    theme: sandstone ## minty also good
    css: styles.css
    toc: true

editor: visual

options:
  warning: false
