---
title: "Education and Awards"
---

## Education

**Johns Hopkins University**\
PhD in Biostatistics (2028 Expected)

Certificate in Health Finance and Management (2025 Expected)

ScM in Biostatistics (2024)

**McGill University**\
BS in Joint Honours Computer Science and Biology, Minor in Mathematics (2022)\
*First Class Honours, Dean’s Multidisciplinary Undegraduate Research List, Dean's Honour List (Top 10%)*

**The Royal Conservatory of Music\
**Associate Diploma (ARCT), Performer in Piano (2014)

## Skills

**Languages:** Python, R, Java, C, Bash, SAS

**Software/Packages:** PyTorch/Tensorflow, Git/GitHub, dashboarding/data visualization, image processing, Factset, yfinance

**Cloud/Databases:** AWS, cluster computing, SQL, REDCap, large Biobank data processing

**Theory:** Deep learning, regression, survival analysis, time-series/functional data analysis, statistics, measure theory probability

**Highlighted Coursework**

[Graduate:]{.underline} 4 terms each of Measure Theory Probability, Statistics, Advanced Methods in Biostatistics, and Statistical Computing.

Machine Learning, Survival Analysis, Multi-Level Modelling, Causal Inference, Advanced Data Science.

[Undergraduate:]{.underline} Object- Oriented Programming, Algorithms and Data Structures, Artificial Intelligence, Discrete Mathematics, Real Analysis, Multivariate Calculus, Linear Algebra, Geometry, ODEs.

## Awards

Gertrude M. Cox Scholarship, American Statistics Association (Honorable Mention, JSM 2024)

Master’s Tuition Scholarship, Johns Hopkins University (2023)

Dean’s Multidisciplinary Undegraduate Research List, McGill (2022)

Dean’s Honour List, McGill (2019-2022)

Wing Hing Chan Scholarship in Science, McGill (2021)

Undergraduate Science Research Award (2021) *From the Natural Sciences and Engineering Research Council of Canada (NSERC), \$7500*

Tomlinson Engagement Award for Mentoring, McGill (2020-2021)

J W McConnell Scholarship, McGill (2018)
