---
title: "Publications"
---

## Peer-reviewed articles

**\* = equal contribution/co-first**


1. Lindquist M A, Smith B B, Kannan A, **Zhao A**, Caffo B (2025). Measuring the Functioning Human Brain. Annual Review of
Statistics and its Application,. https://doi.org/10.1146/annuarev-statistics-040522-100329

2.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C (2023). Evaluating the prediction performance of objective physical activity measures for incident Parkinson’s disease in the UK Biobank. *Journal of Neurology,* 270(12), 5913–5923. https://doi.org/10.1007/s00415-023-11939-0

3.  **Zhao A**, Cui E, Leroux A, Zhou X, Muschelli J, Lindquist M, Crainiceanu C. Objectively measured physical activity using wrist-worn accelerometers as a predictor of incident Alzheimer’s Disease in the UK Biobank. *(submitted)*.

4.  Cui E\*, **Zhao A\***, Crainiceanu C, Leroux A. Inference for the Extended Functional Cox Model: A UK Biobank Case Study *(submitted to Biostatistics)*.

5.  **Zhao A**, Lindquist M, Caffo B. Comparing stochastic model performance with applications to fMRI data *(in preparation)*.

6. Morelli K, Meier SM, **Zhao A**, Choudhury M, Willis M, Barral M, Vogel J. A fluid droplet harvests the force generated by shrinking microtubules in living cells *(submitted to Cell)*.

## Presentations

1.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C. Predicting Time-To-Event Incidence of Alzheimer’s Disease
and Mortality using Objective Physical Activity Measures in the UK Biobank, *10th Annual Joint Session of the BHS Lab, ENGAGE Lab, and SMART-WIT groups*, Johns Hopkins Univeristy, May 2024

2.  Sim S, Morelli K, **Zhao A**, Vogel J. L'effet de la phosphorylation de la tubuline-y sur la kinésine-5 et sur la formation de paires de microtubules dans le fuseau mitotique, *90e Congrès de l’ACFAS*, Université de Montréal, May 2023

3.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C. Physical activity to predict Parkinson's disease in the UK Biobank, *8th Annual Joint Session of the BHS Lab, ENGAGE Lab, and SMART-WIT groups*, Johns Hopkins Univeristy, April 2023

4.  Sim S, Morelli K, **Zhao A**, Vogel J. Le rôle de la phosphorylation de la tubuline-y dans l’organisation des microtubules du fuseau mitotique médiée par la kinésine-5, *89e Congrès de l’ACFAS*, Université de Montréal, May 2022

## Posters and Abstracts

1.  Morelli K, Meier SM, **Zhao A**, Willis M, Barral Y, Vogel J. Interrogating the material properties of a microtubule (+) end-associated nanoscale condensate in living cells using super-resolution microscopy, *American Society for Cell Biology Cell Bio Virtual*, 2023

2.  Sim S, **Zhao A**, Vogel J. Phosphoregulation of y-tubulin regulates anti-parallel microtubule bundling through kinesin-5, *8th Meeting of the International Union of Microbeam Analysis Societies*, 2023

3.  Sim S, **Zhao A**, Vogel J. y-Tubulin phosphoregulation controls interpolar microtubule organization through kinesin-5, *Mitotic spindle: From living and synthetic systems to theory*, 2023

4.  Sim S, Morelli K, **Zhao A**, Vogel J. How does y-tubulin phosphoregulation control microtubule identity during spindle assembly?, *4th Annual CRBS Symposium*, Montreal, Canada, 2022

5.  Sim S, Morelli K, **Zhao A**, Vogel J. Phosphoregulation of y-Tubulin Directs Spindle Assembly Through Kinesin-5 and Microtubule Number, *American Society for Cell Biology Cell Bio Virtual*, 2021
