project:
  type: website

website:
  title: "Angela Zhao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - publications.qmd
      - work.qmd

    right:
      - icon: github
        href: https://github.com/ang-zhao?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/angela0zhao/
format:
  html:
    theme: sandstone ## minty also good
    css: styles.css
    toc: true

editor: visual

